// <auto-generated />
using System;
using Kemudi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kemudi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812035049_UpdateVehicleMaxSpeed70Kmh")]
    partial class UpdateVehicleMaxSpeed70Kmh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Kemudi.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Dasar keseimbangan, pengereman, dan bermanuver.",
                            Slug = "kursus-motor",
                            Title = "Kursus Motor",
                            VehicleType = "MOTOR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "Dari nol hingga siap ambil SIM A.",
                            Slug = "kursus-mobil",
                            Title = "Kursus Mobil",
                            VehicleType = "MOBIL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Description = "Persiapan SIM B1/B2.",
                            Slug = "kursus-truk",
                            Title = "Kursus Truk",
                            VehicleType = "TRUK"
                        });
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.CoursePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Includes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionDurationMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sessions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("CoursePackages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CourseId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Dasar keseimbangan, pengereman, dan bermanuver di lalu lintas ringan.",
                            Includes = "4x sesi praktik simulasi 60 menit\n1x sesi teori rambu & etika berkendara\nAkses materi Motor selamanya\nSertifikat kelulusan digital",
                            Label = "Motor Reguler",
                            Level = "Pemula",
                            Price = 350000m,
                            SessionDurationMin = 60,
                            Sessions = 4,
                            Slug = "motor-reguler"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CourseId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Untuk yang ingin lebih mahir bermanuver di jalan padat dan tikungan tajam.",
                            Includes = "6x sesi praktik simulasi 60 menit\nEvaluasi progres tiap 2 sesi\n1-on-1 dengan mentor pilihan\nAkses materi Motor selamanya\nSertifikat kelulusan digital",
                            Label = "Motor Intensif",
                            Level = "Menengah",
                            Price = 550000m,
                            SessionDurationMin = 60,
                            Sessions = 6,
                            Slug = "motor-intensif"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CourseId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "Kursus paling populer — dari nol hingga siap ambil SIM A.",
                            Includes = "8x sesi praktik simulasi 60 menit\n2x sesi teori (rambu & parkir)\nAkses materi Mobil selamanya\nSertifikat kelulusan digital",
                            Label = "Mobil Reguler",
                            Level = "Pemula",
                            Price = 1200000m,
                            SessionDurationMin = 60,
                            Sessions = 8,
                            Slug = "mobil-reguler"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CourseId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "Lebih banyak jam terbang untuk parkir paralel, tanjakan, dan jalan tol.",
                            Includes = "12x sesi praktik simulasi 60 menit\nEvaluasi progres tiap 3 sesi\n1-on-1 dengan mentor pilihan\nSimulasi ujian SIM A\nAkses materi Mobil selamanya\nSertifikat kelulusan digital",
                            Label = "Mobil Intensif",
                            Level = "Menengah",
                            Price = 1950000m,
                            SessionDurationMin = 60,
                            Sessions = 12,
                            Slug = "mobil-intensif"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CourseId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "Teknik defensive driving untuk kondisi jalan licin, ramai, dan darurat.",
                            Includes = "10x sesi praktik simulasi 75 menit\nSkenario cuaca & jalan licin\n1-on-1 dengan mentor senior pilihan\nSertifikat kelulusan digital",
                            Label = "Mobil Mahir Defensive Driving",
                            Level = "Mahir",
                            Price = 2600000m,
                            SessionDurationMin = 75,
                            Sessions = 10,
                            Slug = "mobil-mahir"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            CourseId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Description = "Persiapan SIM B1, fokus jarak pengereman panjang dan radius belok lebar.",
                            Includes = "10x sesi praktik simulasi 90 menit\n2x sesi teori muatan & keselamatan\n1-on-1 dengan mentor pilihan\nAkses materi Truk selamanya\nSertifikat kelulusan digital",
                            Label = "Truk Reguler",
                            Level = "Menengah",
                            Price = 3200000m,
                            SessionDurationMin = 90,
                            Sessions = 10,
                            Slug = "truk-reguler"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            CourseId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Description = "Untuk calon pengemudi profesional — manuver di area sempit dan mundur presisi.",
                            Includes = "14x sesi praktik simulasi 90 menit\nSkenario mundur & parkir area sempit\n1-on-1 dengan mentor senior pilihan\nSimulasi ujian SIM B1\nSertifikat kelulusan digital",
                            Label = "Truk Profesional",
                            Level = "Mahir",
                            Price = 4500000m,
                            SessionDurationMin = 90,
                            Sessions = 14,
                            Slug = "truk-profesional"
                        });
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.CourseRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CoursePackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIK")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoursePackageId");

                    b.HasIndex("Email");

                    b.HasIndex("MentorId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseRegistrations");
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentsTrained")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestimonialsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Mentors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Achievements = "Membimbing lebih dari 480 murid dengan tingkat kelulusan SIM 94%\nInstruktur terbaik Kemudi.id 2024 & 2025",
                            AvatarColor = "#3b82f6",
                            Bio = "Mantan instruktur di sekolah mengemudi berlisensi Jakarta, spesialis membimbing pemula yang gugup di jalan ramai.",
                            Certifications = "Lisensi Instruktur Mengemudi Nasional (LIMN)\nSertifikasi Defensive Driving — Rifat Drive Labs",
                            ExperienceYears = 12,
                            Initials = "BS",
                            Name = "Budi Santoso",
                            Phone = "+62 812-3456-7890",
                            Rating = 4.9000000000000004,
                            Slug = "budi-santoso",
                            StudentsTrained = 480,
                            TestimonialsJson = "[{\"name\":\"Sarah A.\",\"quote\":\"Sabar banget jelasinnya, dari yang takut nyetir jadi PD di tol.\"},{\"name\":\"Doni P.\",\"quote\":\"Cara ngajar parkir paralelnya gampang diikuti, langsung bisa!\"}]",
                            Title = "Instruktur Senior Mobil & Motor",
                            VehicleTypes = "MOTOR,MOBIL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            Achievements = "Pembicara workshop keselamatan berkendara wanita 2023\nRating kepuasan murid rata-rata 4.8/5 dari 300+ ulasan",
                            AvatarColor = "#ec4899",
                            Bio = "Fokus pada teknik defensive driving dan kesiapan menghadapi kondisi jalan licin atau darurat.",
                            Certifications = "Certified Defensive Driving Instructor — Global Defensive Driving\nSertifikasi P3K Berkendara",
                            ExperienceYears = 8,
                            Initials = "SR",
                            Name = "Siti Rahma",
                            Phone = "+62 811-2345-678",
                            Rating = 4.7999999999999998,
                            Slug = "siti-rahma",
                            StudentsTrained = 310,
                            TestimonialsJson = "[{\"name\":\"Rina K.\",\"quote\":\"Diajarin cara reaksi kalau tiba-tiba ada motor nyelip, berasa banget manfaatnya.\"}]",
                            Title = "Instruktur Mobil & Defensive Driving",
                            VehicleTypes = "MOBIL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            Achievements = "15 tahun pengalaman mengemudikan truk logistik lintas provinsi\nMembimbing 210+ murid lulus ujian SIM B1",
                            AvatarColor = "#16a34a",
                            Bio = "Eks pengemudi logistik antarkota, ahli mengajarkan manuver truk di area sempit dan teknik mundur presisi.",
                            Certifications = "Sertifikasi Instruktur SIM B1/B2 — Kemenhub\nSertifikasi Keselamatan Muatan & Logistik",
                            ExperienceYears = 15,
                            Initials = "AW",
                            Name = "Agus Wirawan",
                            Phone = "+62 813-9876-5432",
                            Rating = 4.9000000000000004,
                            Slug = "agus-wirawan",
                            StudentsTrained = 210,
                            TestimonialsJson = "[{\"name\":\"Hendra S.\",\"quote\":\"Diajarin trik mundur ke gang sempit, sekarang kerja jadi sopir truk perusahaan.\"}]",
                            Title = "Instruktur Truk & Kendaraan Besar",
                            VehicleTypes = "TRUK,MOBIL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            Achievements = "Membimbing 260+ murid pemula tanpa insiden jatuh selama kursus\nKontributor materi Dasar Berkendara Motor di Kemudi.id",
                            AvatarColor = "#f97316",
                            Bio = "Spesialis melatih pemula yang baru pertama kali naik motor, dengan pendekatan santai dan bertahap.",
                            Certifications = "Lisensi Instruktur Mengemudi Nasional (LIMN)",
                            ExperienceYears = 6,
                            Initials = "DL",
                            Name = "Dewi Lestari",
                            Rating = 4.7000000000000002,
                            Slug = "dewi-lestari",
                            StudentsTrained = 260,
                            TestimonialsJson = "[{\"name\":\"Putri N.\",\"quote\":\"Awalnya takut banget sama motor, sekarang udah berani ke kampus naik motor sendiri.\"}]",
                            Title = "Instruktur Motor",
                            VehicleTypes = "MOTOR"
                        });
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.SimulationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObstacleHits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("OffRoadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<long>("TimeTakenMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("TrainingMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Violations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("SimulationAttempts");
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Acceleration")
                        .HasColumnType("REAL");

                    b.Property<double>("Braking")
                        .HasColumnType("REAL");

                    b.Property<double>("CameraDistance")
                        .HasColumnType("REAL");

                    b.Property<double>("CameraHeight")
                        .HasColumnType("REAL");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Friction")
                        .HasColumnType("REAL");

                    b.Property<int>("GearCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GearRatios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LeanAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxSteerAngle")
                        .HasColumnType("REAL");

                    b.Property<double>("ReverseMaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("SteerRate")
                        .HasColumnType("REAL");

                    b.Property<double>("TireGrip")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Wheelbase")
                        .HasColumnType("REAL");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Acceleration = 9.0,
                            Braking = 12.0,
                            CameraDistance = 5.0,
                            CameraHeight = 2.5,
                            Color = "#f97316",
                            Description = "Lincah dan cepat, tapi sempit dan rawan oleng.",
                            Friction = 3.5,
                            GearCount = 4,
                            GearRatios = "3,1,9,1,35,1",
                            Height = 1.1000000000000001,
                            Label = "Motor",
                            LeanAmount = 0.34999999999999998,
                            Length = 1.8,
                            MaxSpeed = 19.440000000000001,
                            MaxSteerAngle = 0.59999999999999998,
                            ReverseMaxSpeed = 4.0,
                            SteerRate = 6.0,
                            TireGrip = 9.0,
                            Type = "MOTOR",
                            Wheelbase = 1.1000000000000001,
                            Width = 0.59999999999999998
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Acceleration = 6.0,
                            Braking = 9.0,
                            CameraDistance = 8.0,
                            CameraHeight = 3.2000000000000002,
                            Color = "#3b82f6",
                            Description = "Seimbang antara kecepatan dan kendali.",
                            Friction = 2.5,
                            GearCount = 5,
                            GearRatios = "3,4,2,2,1,6,1,25,1",
                            Height = 1.3999999999999999,
                            Label = "Mobil",
                            LeanAmount = 0.080000000000000002,
                            Length = 4.2000000000000002,
                            MaxSpeed = 19.440000000000001,
                            MaxSteerAngle = 0.55000000000000004,
                            ReverseMaxSpeed = 6.0,
                            SteerRate = 4.5,
                            TireGrip = 9.0,
                            Type = "MOBIL",
                            Wheelbase = 2.6000000000000001,
                            Width = 1.8
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Acceleration = 3.2000000000000002,
                            Braking = 4.5,
                            CameraDistance = 13.0,
                            CameraHeight = 5.0,
                            Color = "#16a34a",
                            Description = "Besar dan berat, radius putar lebar, jarak rem panjang.",
                            Friction = 1.8,
                            GearCount = 6,
                            GearRatios = "4,2,3,2,3,1,75,1,3,1",
                            Height = 2.6000000000000001,
                            Label = "Truk",
                            LeanAmount = 0.040000000000000001,
                            Length = 7.5,
                            MaxSpeed = 19.440000000000001,
                            MaxSteerAngle = 0.40000000000000002,
                            ReverseMaxSpeed = 4.0,
                            SteerRate = 2.0,
                            TireGrip = 6.0,
                            Type = "TRUK",
                            Wheelbase = 4.5,
                            Width = 2.3999999999999999
                        });
                });

            modelBuilder.Entity("Kemudi.Infrastructure.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIK")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.CoursePackage", b =>
                {
                    b.HasOne("Kemudi.Domain.Entities.Course", "Course")
                        .WithMany("Packages")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.CourseRegistration", b =>
                {
                    b.HasOne("Kemudi.Domain.Entities.CoursePackage", "CoursePackage")
                        .WithMany()
                        .HasForeignKey("CoursePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kemudi.Domain.Entities.Mentor", "Mentor")
                        .WithMany("Registrations")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoursePackage");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Kemudi.Domain.Entities.CourseRegistration", "Registration")
                        .WithMany("Payments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.TrainingSession", b =>
                {
                    b.HasOne("Kemudi.Domain.Entities.CourseRegistration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Kemudi.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Kemudi.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kemudi.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Kemudi.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.Course", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.CourseRegistration", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Kemudi.Domain.Entities.Mentor", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
