<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Kemudi.DataMigration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kemudi.Domain\Kemudi.Domain.csproj" />
    <ProjectReference Include="..\..\src\Kemudi.Infrastructure\Kemudi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
